### ISSUE TITLE
qq 官方机器人获取不到 nickname

### ISSUE THREAD

**Issue by webB1an** [zgojin/astrbot_plugin_niuniu#13]
和群友比划的时候，发现比划不了，去查看了下数据发现 nickname 是空的，牛牛数据大概如下

```
A4ADE679F1BA1A8C54EF30F3C4DEACC4:
  168632D223E21052F41F1E9879B2E84B:
    hardness: 1
    length: 5
    nickname: ''
  CE77AF458D4428529EC9962DCD3268E6:
    hardness: 2
    length: 8
    nickname: ''
  plugin_enabled: true
B676457813FC36493BDF57F373203210:
  CE77AF458D4428529EC9962DCD3268E6:
    hardness: 2
    length: 10
    nickname: ''
  plugin_enabled: true
```
